# Generated by Django 5.0.6 on 2024-07-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionText', models.CharField(default=None, max_length=500)),
                ('QuestionImg', models.ImageField(default=None, upload_to='static/question')),
                ('Option1Text', models.CharField(default=None, max_length=100)),
                ('Option1Img', models.ImageField(default=None, upload_to='static/options')),
                ('Option2Text', models.CharField(default=None, max_length=100)),
                ('Option2Img', models.ImageField(default=None, upload_to='static/options')),
                ('Option3Text', models.CharField(default=None, max_length=100)),
                ('Option3Img', models.ImageField(default=None, upload_to='static/options')),
                ('Option4Text', models.CharField(default=None, max_length=100)),
                ('Option4Img', models.ImageField(default=None, upload_to='static/options')),
                ('CorrectOptionText', models.CharField(default=None, max_length=100)),
                ('CorrectOptionImg', models.ImageField(default=None, upload_to='static/correctoptions')),
                ('QuestionType', models.CharField(default=None, max_length=50)),
                ('QuestionSubject', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
