# Generated by Django 5.0.6 on 2024-07-11 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionData',
            new_name='QuestionData1',
        ),
    ]
