# Generated by Django 5.0.6 on 2024-07-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_questiondata_questiondata1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionData1',
            new_name='QuestionData',
        ),
    ]
