# Generated by Django 5.0.6 on 2024-07-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_questiondata1_questiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondata',
            name='CorrectOptionImg',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/correctoptions'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='CorrectOptionText',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='Option1Img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/options'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='Option1Text',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='Option2Img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/options'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='Option2Text',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='Option3Img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/options'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='Option3Text',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='Option4Img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/options'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='Option4Text',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='QuestionImg',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/question'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='QuestionSubject',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='QuestionText',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='QuestionType',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
