# Generated by Django 5.0.6 on 2024-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_questiondata_correctoptionimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerImg', models.ImageField(default='BannerImage', upload_to='static/Banner')),
                ('BannerType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quote', models.CharField(max_length=100)),
            ],
        ),
    ]
